jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MAILERSEND_API_KEY: ${{ secrets.MAILERSEND_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Streamlit
        run: streamlit run decompte_soir.py
